docs: gradle.yml S3 관련 추가

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -55,22 +55,64 @@ jobs:
     - name: Change Name of Jar File
       run: mv ./build/libs/*SNAPSHOT.jar ./cicdtest.jar
 
+    # S3 연결 확인
+    - name: Check S3 Health
+      run: |
+        echo "Performing S3 health check..."
+        if aws s3api head-bucket --bucket ${{ secrets.AWS_S3_BUCKET }} --region ap-northeast-2; then
+          echo "S3 connection successful."
+        else
+          echo "Failed to connect to S3."
+          exit 1
+        fi
+
+     # S3에 JAR 파일 업로드
+    - name: Upload to S3
+      run: |
+        aws s3 cp cicdtest.jar s3://${{ secrets.AWS_S3_BUCKET }}/ureca/cicdtest.jar --acl public-read
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        AWS_DEFAULT_REGION: ap-northeast-2
+
+    # # 빌드한 것을 버킷에 배포 
+    # - name: Sync Bucket
+    #   env:
+    #     AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
+    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
+    #     AWS_EC2_METADATA_DISABLED: true
+    #   run: |
+    #     aws s3 sync \
+    #       --region ap-northeast-2 \
+    #       build s3://urecabucket/cicdtest-.jar \
+    #       --delete
+
     # 이름 변경된 cicdtest.jar 파일 EC2로 전송 
-    - name: Transfer the Jar File to EC2
-      uses: appleboy/scp-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ${{ secrets.EC2_USERNAME }}
-        key: ${{ secrets.EC2_KEY }}
-        source: cicdtest.jar
-        target: /home/ubuntu
+    # - name: Transfer the Jar File to EC2
+    #   uses: appleboy/scp-action@master
+    #   with:
+    #     host: ${{ secrets.EC2_HOST }}
+    #     username: ${{ secrets.EC2_USERNAME }}
+    #     key: ${{ secrets.EC2_KEY }}
+    #     source: cicdtest.jar
+    #     target: /home/ubuntu
 
   # 배포 작업
   deploy: 
     runs-on: ubuntu-latest
     needs: build # build 작업이 완료된 후 실행
     steps:
-    # ec2 접속 후 jar 파일 실행
+    
+    # S3에서 Jar 파일 다운
+    - name: Download JAR file from S3
+      run: |
+        aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/ureca/cicdtest.jar ./cicdtest.jar
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        AWS_DEFAULT_REGION: ap-northeast-2
+      
+    # ec2 접속 후 Jar 파일 실행
     - name: Execute jar file on EC2
       uses: appleboy/ssh-action@v0.1.10
       with:
